build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest

args:
  BUILD_ARCH: $BUILD_ARCH
  BUILD_VERSION: $BUILD_VERSION
  BUILD_FROM: $BUILD_FROM

labels:
  org.opencontainers.image.title: "MinIO Home Assistant Add-on"
  org.opencontainers.image.description: "S3-compatible object storage for Home Assistant"
  org.opencontainers.image.source: "https://github.com/watsonpaul80/minio-ha-addon"
  org.opencontainers.image.version: "${BUILD_VERSION}"
