name: MinIO
version: "1.1.0"
slug: minio
description: High performance, self-hosted S3 storage server for backups and object storage
startup: services
boot: auto
init: false
advanced: true

url: "https://github.com/watsonpaul80/minio-ha-addon"
watchdog: "http://[HOST]:[PORT:9001]/minio/health/live"
webui: "http://[HOST]:[PORT:9001]"

panel_icon: mdi:server-network
panel_title: MinIO

host_network: false
homeassistant_api: false
hassio_api: false

privileged:
  - NET_ADMIN
  - SYS_ADMIN

options:
  access_key: "admin"
  secret_key: "minio123"
  port: 9000
  console_port: 9001
  storage_path: "/data/minio"
  public_bucket_path: "/share/minio/public"
  enable_ssl: false

schema:
  access_key: str
  secret_key: str
  port: port
  console_port: port
  storage_path: str?
  public_bucket_path: str?
  enable_ssl: bool

arch:
  - aarch64
  - amd64

map:
  - config:rw
  - ssl
  - share:rw
  - backup:rw
  - media:rw
  - addons:rw

ports:
  "9000/tcp": null
  "9001/tcp": 9001
